### ISSUE TITLE
Run Push Server

### ISSUE THREAD

**Issue by maklei125** [lucaconte/BeatTheMaddler#1]
When I try to run the Push server, I get this error "no main manifest attribute, in target/Push-Server-0.12.0.jar". do you know how can i run the Push Server. 
By the way, thank you very much for this tutorial is working perfectly.

**Comment by lucaconte** [comment]
Ok, It's my documentation fault, sorry!
In order to start Push Server use the "capsule" jar:
java -jar Push-Server-0.12.0-capsule-fat.jar server YourPushServerConfigFile.yml

**Comment by maklei125** [comment]
Perfect! thank you very much...
