### ISSUE TITLE
Attatchments storage server configuration.

### ISSUE THREAD

**Issue by psnilesh** [lucaconte/BeatTheMaddler#14]
How can i configure another server for saving all the message attatchments instead of AWS s3? 
Can it be done?

**Comment by lucaconte** [comment]
On ven 31/03/17, 07:38, Nilesh PS wrote:
> How can i configure another server for saving all the message attatchments instead of AWS s3? 
> Can it be done?
Try:
https://minio.io/

-- 
 =========================================================================
| luca.conte@gmail.com                                                    |
| Pub key fingerprint: B664 DAE2 C6D8 8486 E676  BB54 0E6D C27B C969 33A3 |
 =========================================================================
